# Compiler Configuration
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
kotlin.incremental.useClasspathSnapshot=true
# Project Configuration
project.name=NfcNci_Patience
project.android.compileSdk=36
project.android.minSdk=27
project.android.targetSdk=36
project.app.packageName=id.my.pjm.toys.nfcnci_patience
project.app.versionName="0.2.0"
project.app.versionCode=5

