[versions]
agp = "9.0.1"
kotlin = "2.3.10"
xposed = "82"
junit = "4.13.2"

[libraries]
xposed-api = { group = "de.robv.android.xposed", name = "api", version.ref = "xposed" }
junit = { group = "junit", name = "junit", version.ref = "junit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
